import { CONFIG } from "./config.js";
import { seedCases } from "./data.js";
const CK="ic-v2-cases",UK="ic-v2-user";let sb=null,load=null;
const localCases=()=>JSON.parse(localStorage.getItem(CK)||"null")||structuredClone(seedCases);
const saveCases=x=>localStorage.setItem(CK,JSON.stringify(x));
const localUser=()=>JSON.parse(localStorage.getItem(UK)||"null")||{score:72,judged:0,streak:0,votes:{}};
const saveUser=x=>localStorage.setItem(UK,JSON.stringify(x));
export const isLive=()=>!!(CONFIG.supabaseUrl&&CONFIG.supabaseAnonKey&&!CONFIG.demoMode);
async function client(){if(!isLive())return null;if(!load)load=Promise.race([import("https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2/+esm").then(({createClient})=>sb=createClient(CONFIG.supabaseUrl,CONFIG.supabaseAnonKey)),new Promise((_,reject)=>setTimeout(()=>reject(new Error("Supabase client load timed out")),12000))]).catch(()=>null);return sb||await load}
export async function getSession(){const x=await client();if(!x)return{user:null};const r=await x.auth.getSession();return{user:r.data.session?.user||null}}
export async function signIn(email){const x=await client();return x.auth.signInWithOtp({email,options:{emailRedirectTo:location.href.split("#")[0]}})}
export async function signOut(){const x=await client();if(x)await x.auth.signOut()}
const row=c=>({id:c.id,category:c.category,title:c.title,summary:c.summary,sideA:c.side_a,sideB:c.side_b,votes:{guilty:0,innocent:0,both:0}});
export async function listCases(cat="All"){const x=await client();if(!x)return localCases().filter(c=>cat==="All"||c.category===cat);const r=await x.from("cases").select("id,category,title,summary,side_a,side_b").eq("status","open").order("created_at",{ascending:false});if(r.error)throw r.error;const ids=(r.data||[]).map(c=>c.id),q=ids.length?await x.rpc("get_case_vote_counts",{p_case_ids:ids}):{data:[],error:null};if(q.error)throw q.error;const m={};for(const c of q.data||[])m[c.case_id]={guilty:+c.guilty||0,innocent:+c.innocent||0,both:+c.both||0};return(r.data||[]).map(c=>({...row(c),votes:m[c.id]||{guilty:0,innocent:0,both:0}}))}
export async function getCase(id){const x=await client();if(!x)return localCases().find(c=>c.id===id)||null;const r=await x.from("cases").select("id,category,title,summary,side_a,side_b").eq("id",id).maybeSingle();if(r.error)throw r.error;if(!r.data)return null;const q=await x.rpc("get_case_vote_counts",{p_case_ids:[id]});if(q.error)throw q.error;const v=q.data?.[0]||{};return{...row(r.data),votes:{guilty:+v.guilty||0,innocent:+v.innocent||0,both:+v.both||0}}}
export async function myVote(id){const x=await client();if(!x)return localUser().votes[id]||null;const u=(await x.auth.getUser()).data.user;if(!u)return null;const r=await x.from("votes").select("verdict").eq("case_id",id).eq("user_id",u.id).maybeSingle();return r.data?.verdict||null}
export async function castVote(id,v){const x=await client();if(!x){const cs=localCases(),u=localUser(),c=cs.find(z=>z.id===id);if(!c||u.votes[id])return; c.votes[v]++;u.votes[id]=v;u.judged++;u.streak++;saveCases(cs);saveUser(u);return}const r=await x.rpc("cast_vote",{p_case_id:id,p_verdict:v});if(r.error)throw r.error;return r.data}
export async function createCase(d){const x=await client();if(!x){const cs=localCases(),id="case-"+(18475+cs.length);cs.unshift({id,category:d.category,title:d.title,summary:d.summary,sideA:d.sideA,sideB:d.sideB,votes:{guilty:0,innocent:0,both:0}});saveCases(cs);return id}const r=await x.rpc("create_case",{p_category:d.category,p_title:d.title,p_summary:d.summary,p_side_a:d.sideA,p_side_b:d.sideB});if(r.error)throw r.error;return r.data}
export async function reportCase(id,reason,details){const x=await client();if(!x)return;const r=await x.rpc("submit_report",{p_case_id:id,p_reason:reason,p_details:details||""});if(r.error)throw r.error}
export async function getProfile(){const x=await client();if(!x)return localUser();const u=(await x.auth.getUser()).data.user;if(!u)return{score:0,judged:0,streak:0,votes:{}};const r=await x.from("profiles").select("judge_score,cases_judged,current_streak,display_name").eq("id",u.id).single();if(r.error)throw r.error;return{score:r.data.judge_score,judged:r.data.cases_judged,streak:r.data.current_streak,votes:{},displayName:r.data.display_name}}
export const localProfile=localUser;
export async function updateProfile(name){const x=await client();if(!x){const u=localUser();u.displayName=name;saveUser(u);return}const r=await x.from("profiles").update({display_name:String(name).trim()}).eq("id",(await x.auth.getUser()).data.user.id);if(r.error)throw r.error}
export async function listLeaderboard(n=20){const x=await client();if(!x)return[{displayName:"Anonymous Judge",score:localUser().score,judged:localUser().judged,streak:localUser().streak}];const r=await x.from("profiles").select("id,display_name,judge_score,cases_judged,current_streak").order("judge_score",{ascending:false}).limit(n);if(r.error)throw r.error;return(r.data||[]).map((z,i)=>({rank:i+1,displayName:z.display_name,score:z.judge_score,judged:z.cases_judged,streak:z.current_streak}))}
export async function isModerator(){const x=await client();if(!x)return false;const r=await x.rpc("is_moderator");if(r.error)throw r.error;return!!r.data}
export async function listModerationReports(){const x=await client();if(!x)return[];const r=await x.rpc("moderator_list_reports");if(r.error)throw r.error;return r.data||[]}
export async function setCaseStatus(id,status,note=""){const r=await client().then(x=>x.rpc("moderator_set_case_status",{p_case_id:id,p_status:status,p_note:note}));if(r.error)throw r.error}
export async function resolveReport(id,status,note=""){const r=await client().then(x=>x.rpc("moderator_resolve_report",{p_report_id:id,p_status:status,p_note:note}));if(r.error)throw r.error}